services:
  mysql:
    container_name: mysql
    restart:
      always
    image: mysql:8.0.30
    ports:
      - 3306:3306
    networks:
      - auth_network
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
  go_auth_jwt:
    container_name: go_auth_jwt
    restart:
      always
    image: go_auth_jwt:1.0
    ports:
      - 9000:9000
    depends_on:
      - mysql
    networks:
      - auth_network
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=YOUR_PASSWORD
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=YOUR_DB
    volumes:
      - auth_db_mysql:/data/db

volumes:
  auth_db_mysql:

networks:
  auth_network:
    name: auth_network
