GET http://localhost:9000/ HTTP/1.1

###
POST http://localhost:9000/signup HTTP/1.1
Content-Type: application/json

{
    "name": "Kodarullah",
    "email": "warning@aa.com",
    "password": "123456"
}

###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
    "email": "wiuewiue",
    "password": "123456"
}

###
GET http://localhost:9000/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY5MDUxMTgsInVzZXJfaWQiOjE0fQ.CSH6gkLwnDVVa_9bYk43bOTFnTxPSm6c6OeKzR8sg_s
